name: local_microdotnet_statemachines

services:
    local.microdotnet.services.statemachines.eventstore:
        container_name: local.microdotnet.services.statemachines.eventstore
        hostname: local.microdotnet.services.statemachines.eventstore
        image: eventstore/eventstore:22.10.0-buster-slim
        restart: always
        networks:
            - local.microdotnet.services.statemachines
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=10001
            - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=10002
        ports:
            - "10001:1113"
            - "10002:2113"
        volumes:
            - type: volume
              source: eventstore-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-logs
              target: /var/log/eventstore

    local.microdotnet.services.statemachines.mongo:
        container_name: local.microdotnet.services.statemachines.mongo
        hostname: local.microdotnet.services.statemachines.mongo
        image: mongo:8.0.1
        restart: always
        networks:
            - local.microdotnet.services.statemachines
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 10003:27017
        volumes:
            - mongo-configdb:/data/configdb
            - mongo-volume:/data/db

    local.microdotnet.services.statemachines.mongoexpress:
        container_name: local.microdotnet.services.statemachines.mongoexpress
        hostname: local.microdotnet.services.statemachines.mongoexpress
        image: mongo-express:1.0.2-20-alpine3.19
        restart: always
        networks:
            - local.microdotnet.services.statemachines
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://root:password@local.microdotnet.services.statemachines.mongo:27017
        ports:
            - 10004:8081
        depends_on:
            - local.microdotnet.services.statemachines.mongo

    local.microdotnet.services.statemachines.webapi:
        container_name: local.microdotnet.services.statemachines.webapi
        hostname: local.microdotnet.services.statemachines.webapi
        image: microdotnet.services.statemachines:local
        restart: always
        environment:
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__EventsDB=esdb://local.microdotnet.services.statemachines.eventstore:2113/?tls=false
            - ConnectionStrings__ReadDB=mongodb://root:password@local.microdotnet.services.statemachines.mongo:27017
        networks:
            - local.microdotnet.services.statemachines
        ports:
            - 10005:80
        depends_on:
            - local.microdotnet.services.statemachines.eventstore
            - local.microdotnet.services.statemachines.mongo

networks:
    local.microdotnet.services.statemachines:
        driver: bridge

volumes:
    eventstore-data:
    eventstore-logs:
    mongo-configdb:
    mongo-volume:
    esdata:
    elasticagent-data:
