@WebApi_HostAddress = http://localhost:7031

POST {{WebApi_HostAddress}}/v1/machineDefinitions
Content-Type: application/json

{
    "code": "Test",
    "name": "Test machine",
    "description": "Description of test machine"
}

###

GET {{WebApi_HostAddress}}/v1/machineDefinitions/Test
Accept: application/json

###
